### ISSUE TITLE
bug in luis.js

### ISSUE THREAD

**Issue by CzBuCHi** [tomitrescak/luis#14]
$ luis --init
C:\projects\testing\node_modules\luis\luis.js:34
  let configPath = path.resolve(file);
                                ^

ReferenceError: file is not defined
    at Object.<anonymous> (C:\projects\testing\node_modules\luis\luis.js:34:33)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

---
these changes fixed that, but not sure if correct
```diff
- 34: let configPath = path.resolve(file);
+ 34: let configPath = path.resolve(run);
- 41: console.log('Creating standard luis config at: ' + file);
+ 41: console.log('Creating standard luis config at: ' + configPath);
```

**Comment by tomitrescak** [comment]
Not sure why it's failing to you. `file` is defined: https://github.com/tomitrescak/luis/blob/master/luis.js#L43

**Comment by tomitrescak** [comment]
I have just done:

```
yarn add luis
yarn luis --init
```

And all went well. Also worked with global luis

```
yarn global add luis
luis --init
```

Am a bit puzzled here. Do you maybe have a repro?

**Comment by tomitrescak** [comment]
Try version 3.2.11, truth is I have been sitting on couple RC's on private npm reposittor and I just published it.

**Comment by CzBuCHi** [comment]
fixed :)
